import type { Metadata } from "next";
import Link from "next/link";
import {
  CheckCircle2,
  ExternalLink,
  Lightbulb,
  Search,
  Target,
  TrendingUp,
  Users,
} from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Research — How We Found TenantPulse",
  description:
    "The research story behind TenantPulse: validation checklist, source pain points, and why this micro-SaaS idea was built.",
};

const checklist = [
  { label: "10+ posts with this pain", passed: true },
  { label: "Paying for inferior solution", passed: true },
  { label: "Reachable channel", passed: true },
  { label: "MVP < 4 weeks", passed: true },
  { label: "Price point high enough", passed: true },
  { label: "Hair-on-fire problem", passed: true },
  { label: "Can pre-sell", passed: true },
  { label: "< 3 competitors", passed: true },
  { label: "AI-agent operable", passed: true },
];

const painPoints = [
  {
    problem:
      "Real estate investors struggle to track finances across multiple properties, understand true value per property, and identify which are generating cash flow vs. costing money.",
    persona: "Real estate investor managing multiple properties",
    workaround: "Juggling multiple spreadsheets to track properties and finances",
    frequency: "weekly",
    wtp: "Built custom dashboard (Earn Clarity) to replace spreadsheets",
    url: "https://www.reddit.com/r/SideProject/comments/1unp3zy/got_tired_of_juggling_spreadsheets_to_track_my/",
  },
  {
    problem:
      "Managing multiple spreadsheets for rental properties is tedious and doesn't provide unified visibility into tenants, maintenance, rent tracking, and financial performance.",
    persona: "Landlord managing multiple rental properties",
    workaround:
      "Managing multiple spreadsheets or ditching property management apps entirely",
    frequency: "weekly",
    wtp: "Built custom Notion system to consolidate property management",
    url: "https://www.reddit.com/r/Notion/comments/1ue3u6b/built_a_notion_system_to_manage_my_rental/",
  },
];

const criteria = [
  {
    icon: Target,
    title: "Self-running micro-SaaS",
    description:
      "One specific problem, a small dedicated user base, minimal manual ops (digital-nomad friendly).",
  },
  {
    icon: Users,
    title: "AI-agent operable",
    description:
      "Daily support, content, and processing handled by autonomous agents on self-hosted LLMs.",
  },
  {
    icon: Search,
    title: "Real pain only",
    description:
      "Every idea traces back to actual posts where people complain or ask 'is there a tool for X?'",
  },
  {
    icon: TrendingUp,
    title: "B2B & recurring revenue",
    description: "Higher willingness to pay, lower churn. Markets with <3 established competitors.",
  },
  {
    icon: Lightbulb,
    title: "MVP in under 4 weeks",
    description: "Solo-dev buildable, no regulatory/hardware/capital barriers.",
  },
];

export default function ResearchPage() {
  return (
    <div className="min-h-screen">
      <Header active="research" />

      <div className="mx-auto max-w-4xl px-6 py-16">
        {/* Hero */}
        <div className="mb-16 text-center">
          <p className="mb-4 text-sm text-accent">Idea Miner Research · Run 2026-07-10-pm</p>
          <h1 className="font-display text-4xl font-bold text-white md:text-5xl">
            Why TenantPulse exists
          </h1>
          <p className="mx-auto mt-4 max-w-2xl text-lg text-slate-400">
            AI agent handles all routine tenant communications — rent reminders, maintenance
            updates, lease renewals.
          </p>
          <div className="mt-6 inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-4 py-2 text-sm text-emerald-400">
            <CheckCircle2 className="h-4 w-4" />
            Scored 105/130 · Passed 9/9 validation checks
          </div>
        </div>

        {/* Why research program exists */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Why this research program exists
          </h2>
          <div className="glass-card p-6 leading-relaxed text-slate-300">
            <p>
              This app was auto-generated by the <strong className="text-white">Idea Miner</strong>{" "}
              pipeline — a twice-daily research program that hunts for validated micro-SaaS
              opportunities from real people expressing real pain online (Reddit, Hacker News,
              Stack Exchange, GitHub, and more).
            </p>
          </div>

          <h3 className="mb-4 mt-8 font-display text-xl font-semibold text-white">
            What we&apos;re looking for
          </h3>
          <div className="grid gap-4 sm:grid-cols-2">
            {criteria.map((c) => (
              <div key={c.title} className="glass-card p-5">
                <c.icon className="mb-3 h-5 w-5 text-accent" />
                <h4 className="font-medium text-white">{c.title}</h4>
                <p className="mt-1 text-sm text-slate-400">{c.description}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Why demo was built */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Why this demo was built
          </h2>
          <div className="glass-card p-6 text-slate-300">
            <p>
              When an idea passes the validation gate (≥8/9 checklist items, not declining on
              Google Trends, not previously built), the pipeline automatically ships a working
              mock on Vercel so we can see the product story, not just a slide deck.
            </p>
          </div>
        </section>

        {/* This specific idea */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            This specific idea
          </h2>
          <div className="glass-card space-y-4 p-6">
            <div className="grid gap-4 sm:grid-cols-2">
              <div>
                <p className="text-xs uppercase text-slate-500">Cluster</p>
                <p className="text-white">Rental Property Financial Tracking</p>
              </div>
              <div>
                <p className="text-xs uppercase text-slate-500">Target customer</p>
                <p className="text-white">
                  Self-managing landlords with 2–15 units
                </p>
              </div>
              <div>
                <p className="text-xs uppercase text-slate-500">Pricing</p>
                <p className="text-white">
                  $5/unit/mo (min $15/mo), capped at $79/mo for 20+ units
                </p>
              </div>
              <div>
                <p className="text-xs uppercase text-slate-500">Go-to-market</p>
                <p className="text-white">
                  r/landlord, r/realestateinvesting, local REI meetups, SEO
                </p>
              </div>
            </div>
            <div className="border-t border-white/10 pt-4">
              <p className="text-xs uppercase text-slate-500">Why we built this demo</p>
              <p className="mt-1 text-slate-300">
                Per-unit pricing makes it affordable for small landlords priced out of enterprise
                tools; AI drafts all outbound messages so landlord only reviews, never writes.
              </p>
            </div>
            <div className="border-t border-white/10 pt-4">
              <p className="text-xs uppercase text-slate-500">Competitive landscape</p>
              <p className="mt-1 text-slate-300">
                Buildium and AppFolio do this but cost $250+/mo and require full platform
                adoption; TurboTenant is free but has no AI communication automation.
              </p>
            </div>
            <div className="border-t border-white/10 pt-4">
              <p className="text-xs uppercase text-slate-500">Agentic automation plan</p>
              <p className="mt-1 text-slate-300">
                Cron agent runs daily: checks rent due dates and sends reminders automatically;
                processes maintenance intake form submissions and drafts replies; triggers lease
                renewal sequences — landlord only approves edge cases flagged by confidence
                scoring.
              </p>
            </div>
          </div>
        </section>

        {/* Validation checklist */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Validation checklist (9/9)
          </h2>
          <div className="glass-card p-6">
            <ul className="grid gap-3 sm:grid-cols-2">
              {checklist.map((item) => (
                <li key={item.label} className="flex items-center gap-2 text-slate-300">
                  <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-400" />
                  {item.label}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* Core MVP features */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Core MVP features
          </h2>
          <ul className="space-y-2">
            {[
              "Tenant directory with lease dates, rent amount, and contact info per unit",
              "Automated rent reminder sequence: SMS/email on day -3, day 0, day +3 of due date",
              "Maintenance request intake form (tenant-facing link); AI drafts landlord acknowledgment and estimated timeline reply",
              "Lease renewal alert 90/60/30 days before expiry with AI-drafted renewal offer letter",
              "Monthly landlord summary: who paid, who is late, open maintenance tickets",
            ].map((feature) => (
              <li
                key={feature}
                className="flex items-start gap-2 rounded-lg bg-surface-raised p-3 text-sm text-slate-300"
              >
                <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" />
                {feature}
              </li>
            ))}
          </ul>
          <p className="mt-4 text-center">
            <Link href="/demo" className="text-accent hover:underline">
              Try all features in the interactive demo →
            </Link>
          </p>
        </section>

        {/* Source pain points */}
        <section className="mb-16">
          <h2 className="mb-6 font-display text-2xl font-bold text-white">
            Source pain points (real posts)
          </h2>
          <div className="space-y-6">
            {painPoints.map((pp) => (
              <article key={pp.url} className="glass-card p-6">
                <p className="text-slate-200">{pp.problem}</p>
                <dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2">
                  <div>
                    <dt className="text-slate-500">Persona</dt>
                    <dd className="text-slate-300">{pp.persona}</dd>
                  </div>
                  <div>
                    <dt className="text-slate-500">Workaround</dt>
                    <dd className="text-slate-300">{pp.workaround}</dd>
                  </div>
                  <div>
                    <dt className="text-slate-500">Frequency</dt>
                    <dd className="text-slate-300">{pp.frequency}</dd>
                  </div>
                  <div>
                    <dt className="text-slate-500">WTP signal</dt>
                    <dd className="text-slate-300">{pp.wtp}</dd>
                  </div>
                </dl>
                <a
                  href={pp.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="mt-4 inline-flex items-center gap-1 text-sm text-accent hover:underline"
                >
                  View source post
                  <ExternalLink className="h-3 w-3" />
                </a>
              </article>
            ))}
          </div>
        </section>

        <p className="text-center text-sm text-slate-500">
          Generated by Idea Miner run 2026-07-10-pm on 2026-07-10 20:51 UTC
        </p>
      </div>

      <Footer />
    </div>
  );
}
